export const GET_TODO_ITEMS = 'GET_TODO_ITEMS';
export const TODO_ITEMS_LOADED = 'TODO_ITEMS_LOADED';
export const ADD_TODO_ITEM = 'ADD_TODO_ITEM';
export const REMOVE_TODO_ITEM = 'REMOVE_TODO_ITEM';
export const UPDATE_TODO_ITEM = 'UPDATE_TODO_ITEM';
